config/routes.rb
Rails.application.routes.draw do
  resources :nutritionists
  resources :clinics
  resources :appointments
  resources :works
  get '/clinics/district/:district' => 'clinics#district'
  root 'pages#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/clinic.rb
class Clinic < ApplicationRecord
    has_many :works
    has_many :nutritionists, through: :works
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/district/:district
  def district
    @clinics = Clinic.where("district = ?", params[:district])

    respond_to do |format|
      if ok
        format.html { redirect_to clinics_url, notice: 'Clinic was found.' }
        format.json { render json: @clinics }
      else
        format.html { notice:"No clinic" }
        format.json { render json: @clinics.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clinic_params
      params.require(:clinic).permit(:name, :street, :parish, :county, :district)
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= form_with(model: clinic, local: true) do |form| %>
  <% if clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
        <% clinic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :parish %>
    <%= form.text_field :parish %>
  </div>

  <div class="field">
    <%= form.label :county %>
    <%= form.text_field :county %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing Clinic</h1>

<%= render 'form', clinic: @clinic %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clinics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Parish</th>
      <th>County</th>
      <th>District</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.name %></td>
        <td><%= clinic.street %></td>
        <td><%= clinic.parish %></td>
        <td><%= clinic.county %></td>
        <td><%= clinic.district %></td>
        <td><%= link_to 'Show', clinic %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New Clinic</h1>

<%= render 'form', clinic: @clinic %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clinic.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @clinic.street %>
</p>

<p>
  <strong>Parish:</strong>
  <%= @clinic.parish %>
</p>

<p>
  <strong>County:</strong>
  <%= @clinic.county %>
</p>

<p>
  <strong>District:</strong>
  <%= @clinic.district %>
</p>

<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>