config/routes.rb
Rails.application.routes.draw do
  resources :nutritionists
  resources :clinics
  resources :appointments
  resources :works
  get '/clinics/district/:district' => 'clinics#district'
  root 'pages#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nutritionist.rb
class Nutritionist < ApplicationRecord
    has_many :works
    has_many :clinics, through: :works
end

app/controllers/nutritionists_controller.rb
class NutritionistsController < ApplicationController
  before_action :set_nutritionist, only: [:show, :edit, :update, :destroy]

  # GET /nutritionists
  # GET /nutritionists.json
  def index
    @nutritionists = Nutritionist.all
  end

  # GET /nutritionists/1
  # GET /nutritionists/1.json
  def show
  end

  # GET /nutritionists/new
  def new
    @nutritionist = Nutritionist.new
  end

  # GET /nutritionists/1/edit
  def edit
  end

  # POST /nutritionists
  # POST /nutritionists.json
  def create
    @nutritionist = Nutritionist.new(nutritionist_params)

    respond_to do |format|
      if @nutritionist.save
        format.html { redirect_to @nutritionist, notice: 'Nutritionist was successfully created.' }
        format.json { render :show, status: :created, location: @nutritionist }
      else
        format.html { render :new }
        format.json { render json: @nutritionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nutritionists/1
  # PATCH/PUT /nutritionists/1.json
  def update
    respond_to do |format|
      if @nutritionist.update(nutritionist_params)
        format.html { redirect_to @nutritionist, notice: 'Nutritionist was successfully updated.' }
        format.json { render :show, status: :ok, location: @nutritionist }
      else
        format.html { render :edit }
        format.json { render json: @nutritionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutritionists/1
  # DELETE /nutritionists/1.json
  def destroy
    @nutritionist.destroy
    respond_to do |format|
      format.html { redirect_to nutritionists_url, notice: 'Nutritionist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nutritionist
      @nutritionist = Nutritionist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nutritionist_params
      params.fetch(:nutritionist, {})
    end
end

app/helpers/nutritionists_helper.rb
module NutritionistsHelper
end

app/views/nutritionists/_form.html.erb
<%= form_with(model: nutritionist, local: true) do |form| %>
  <% if nutritionist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nutritionist.errors.count, "error") %> prohibited this nutritionist from being saved:</h2>

      <ul>
        <% nutritionist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nutritionists/edit.html.erb
<h1>Editing Nutritionist</h1>

<%= render 'form', nutritionist: @nutritionist %>

<%= link_to 'Show', @nutritionist %> |
<%= link_to 'Back', nutritionists_path %>

app/views/nutritionists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nutritionists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nutritionists.each do |nutritionist| %>
      <tr>
        <td><%= link_to 'Show', nutritionist %></td>
        <td><%= link_to 'Edit', edit_nutritionist_path(nutritionist) %></td>
        <td><%= link_to 'Destroy', nutritionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nutritionist', new_nutritionist_path %>

app/views/nutritionists/new.html.erb
<h1>New Nutritionist</h1>

<%= render 'form', nutritionist: @nutritionist %>

<%= link_to 'Back', nutritionists_path %>

app/views/nutritionists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @nutritionist.name %>
</p>

<p>
    <strong>Image_url:</strong>
    <%= @nutritionist.image_url %>
</p>

<p>
    <strong>Number:</strong>
    <%= @nutritionist.number %>
</p>





<%= link_to 'Edit', edit_nutritionist_path(@nutritionist) %> |
<%= link_to 'Back', nutritionists_path %>